### ISSUE TITLE
occure an error about model

### ISSUE THREAD

**Issue by sheng-zhong** [SunnyCYC/aug4mss#4]
I got this error when I run Inference.py
![image](https://user-images.githubusercontent.com/58591074/165048406-505f338a-596d-436f-b7b3-b0e4ca7358ce.png)

**Comment by SunnyCYC** [comment]
Hi, 
Thanks for reporting the error.
I guess that's caused by the shape of tsong_audio. 
It should be 2d as an input for the separate() funciton.

I've modified the code since in my original code soundfile could not read .mp3.
It should work now.

Please let me know if there's any further issues.
Thanks.

**Comment by sheng-zhong** [comment]
> 
it works !  thank u~
